# Generated by Django 5.2.7 on 2025-11-05 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                ("whatsapp", models.CharField(max_length=20, verbose_name="WhatsApp")),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Localisation"),
                ),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub")),
                ("twitter_url", models.URLField(blank=True, verbose_name="Twitter")),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Google Analytics ID"
                    ),
                ),
                (
                    "google_tag_manager_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Google Tag Manager ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Informations de contact",
                "verbose_name_plural": "Informations de contact",
            },
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "duration",
                    models.CharField(
                        help_text="Ex: 3 mois, 40 heures",
                        max_length=50,
                        verbose_name="Durée",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Ex: fa-solid fa-code",
                        max_length=50,
                        verbose_name="Icône Font Awesome",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
            ],
            options={
                "verbose_name": "Formation",
                "verbose_name_plural": "Formations",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "subtitle",
                    models.CharField(max_length=200, verbose_name="Sous-titre"),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="URL slug"),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("application", "Application Mobile"),
                            ("web", "Site Web"),
                            ("cloud", "Solution Cloud"),
                            ("game", "Jeu"),
                        ],
                        default="application",
                        max_length=20,
                        verbose_name="Type de projet",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Pour la liste des projets",
                        verbose_name="Description courte",
                    ),
                ),
                (
                    "full_description",
                    models.TextField(verbose_name="Description complète"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        help_text="Pour la liste des projets",
                        upload_to="projects/covers/",
                        verbose_name="Image de couverture",
                    ),
                ),
                (
                    "header_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/headers/",
                        verbose_name="Image d'en-tête",
                    ),
                ),
                (
                    "video_demo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="projects/videos/",
                        verbose_name="Vidéo de démonstration",
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        help_text="Liste des fonctionnalités principales",
                        verbose_name="Caractéristiques",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Projet mis en avant"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "icon",
                    models.CharField(
                        help_text="Ex: fa-brands fa-python",
                        max_length=50,
                        verbose_name="Icône Font Awesome",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
            ],
            options={
                "verbose_name": "Compétence",
                "verbose_name_plural": "Compétences",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Ex: fa-brands fa-react",
                        max_length=50,
                        verbose_name="Icône Font Awesome",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#667eea",
                        help_text="Code couleur hexadécimal",
                        max_length=7,
                        verbose_name="Couleur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technologie",
                "verbose_name_plural": "Technologies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/screenshots/", verbose_name="Image"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Légende"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="portfolio.project",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capture d'écran",
                "verbose_name_plural": "Captures d'écran",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                to="portfolio.technology", verbose_name="Technologies utilisées"
            ),
        ),
    ]
